### ISSUE TITLE
پیدا کردن روز هفته

### ISSUE THREAD

**Issue by behroozbc** [Saeed-Pooyanfar/jalali-ts#2]
سسلام چطوری میشه روز هفته رو به دست بیاریم؟

**Comment by SaeedDev94** [comment]
You can use native JS Date:

```javascript
const jalali: Jalali = Jalali.now();
const date: Date = jalali.date;
console.log(date.getDay());
```

Ref: **[Date.prototype.getDay()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay)**
